import Link from 'next/link';
import { notFound } from 'next/navigation';

import { buildDemoCaseStudy } from '@/lib/demo/fixtures';
import { HERO_TECHNIQUES } from '@/lib/techniques';

type PageProps = {
  params: Promise<{ id: string }>;
};

export async function generateStaticParams() {
  return [{ id: 'demo-miami-exhibition-teaser' }];
}

export default async function CaseStudyPage({ params }: PageProps) {
  const { id } = await params;
  const study = buildDemoCaseStudy();

  if (id !== study.id) {
    notFound();
  }

  const techniqueNames = study.recommendedTechniqueIds.map(
    (tid) => HERO_TECHNIQUES.find((t) => t.id === tid)?.name ?? tid,
  );

  return (
    <main className="console">
      <p className="eyebrow">Case study</p>
      <h1 style={{ maxWidth: '22ch', margin: '0 0 0.75rem', fontSize: 'clamp(1.6rem, 3.5vw, 2.4rem)' }}>
        {study.brief.objective.slice(0, 80)}…
      </h1>
      <p className="lede" style={{ marginBottom: '1.5rem' }}>
        Shareable workflow report generated by FLORA Field Kit. Demo fixture — replace with
        persisted runs once Techniques are live.
      </p>

      <section className="panel" style={{ marginBottom: '1rem' }}>
        <h2>Original brief</h2>
        <dl className="meta-list" style={{ marginTop: '1rem' }}>
          {(
            [
              ['Objective', study.brief.objective],
              ['Audience', study.brief.audience],
              ['Visual direction', study.brief.visualDirection],
              ['Deliverables', study.brief.deliverables],
              ['Channels', study.brief.channels],
              ['Constraints', study.brief.constraints],
            ] as const
          ).map(([label, value]) => (
            <div key={label}>
              <dt>{label}</dt>
              <dd>{value}</dd>
            </div>
          ))}
        </dl>
      </section>

      <section className="panel" style={{ marginBottom: '1rem' }}>
        <h2>Techniques used</h2>
        <p className="panel__hint">{techniqueNames.join(' → ')}</p>
        <div className="review-grid">
          {study.steps.map((step) => {
            const technique = HERO_TECHNIQUES.find((t) => t.id === step.techniqueId);
            return (
              <article key={step.techniqueId} className="technique-card">
                <h3>{technique?.name ?? step.techniqueId}</h3>
                <p>Status: {step.status} · Charged ${step.chargedCost.toFixed(2)}</p>
                <ul style={{ margin: 0, paddingLeft: '1.1rem', color: 'var(--ink-muted)' }}>
                  {step.outputs.map((o) => (
                    <li key={o.outputId}>
                      {o.name}
                      {o.favorited ? ' (selected)' : ''}
                    </li>
                  ))}
                </ul>
              </article>
            );
          })}
        </div>
      </section>

      <section className="panel" style={{ marginBottom: '1rem' }}>
        <h2>Selected direction</h2>
        <p className="panel__hint">{study.selectedDirection}</p>
        <h2 style={{ marginTop: '1.25rem' }}>Creative reasoning</h2>
        <p className="panel__hint">{study.creativeReasoning}</p>
      </section>

      <section className="panel">
        <h2>Explorations</h2>
        <div className="review-grid" style={{ marginTop: '1rem' }}>
          {study.steps.flatMap((step) =>
            step.outputs
              .filter((o) => o.type === 'imageUrl')
              .map((output) => (
                <figure key={`${step.techniqueId}-${output.outputId}`} className="review-card">
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img src={output.value} alt={output.name} />
                  <figcaption>
                    <strong>{output.name}</strong>
                  </figcaption>
                </figure>
              )),
          )}
        </div>
      </section>

      <p style={{ marginTop: '1.5rem' }}>
        <Link href="/">← Back to Field Kit</Link>
      </p>
      <footer className="console__footer">
        <p>Not affiliated with or endorsed by FLORA.</p>
      </footer>
    </main>
  );
}
